local M = {}

local function hi(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

function M.load(c)
  -- ── Base UI ────────────────────────────────────────────────────────
  hi("Normal",        { fg = c.fg,      bg = c.bg })
  hi("NormalFloat",   { fg = c.fg,      bg = c.float_bg })
  hi("NormalNC",      { fg = c.fg,      bg = c.bg })
  hi("CursorLine",    { bg = c.cursorline })
  hi("CursorLineNr",  { fg = c.keyword, bg = c.cursorline })
  hi("Visual",        { bg = c.visual })
  hi("Search",        { fg = c.bg,      bg = c.warning })
  hi("IncSearch",     { fg = c.bg,      bg = c.keyword })
  hi("StatusLine",    { fg = c.fg,      bg = c.ui_dark })
  hi("StatusLineNC",  { fg = c.comment, bg = c.ui_dark })
  hi("WinSeparator",  { fg = c.ui_mid })
  hi("VertSplit",     { fg = c.ui_mid })  -- deprecated alias for WinSeparator, kept for compat
  hi("LineNr",        { fg = c.comment })
  hi("SignColumn",    { bg = c.bg })
  hi("Pmenu",         { fg = c.fg,      bg = c.ui_dark })
  hi("PmenuSel",      { fg = c.bg,      bg = c.keyword })
  hi("PmenuSbar",     { bg = c.ui_mid })
  hi("PmenuThumb",    { bg = c.fg })
  hi("Folded",        { fg = c.comment, bg = c.cursorline })
  hi("TabLine",       { fg = c.comment, bg = c.ui_dark })
  hi("TabLineSel",    { fg = c.fg,      bg = c.bg })
  hi("TabLineFill",   { bg = c.ui_dark })

  -- ── Legacy syntax ──────────────────────────────────────────────────────
  hi("Comment",      { fg = c.comment,     italic = true })
  hi("Keyword",      { fg = c.keyword })
  hi("Statement",    { fg = c.keyword })
  hi("Conditional",  { fg = c.keyword })
  hi("Repeat",       { fg = c.keyword })
  hi("Label",        { fg = c.keyword })
  hi("Exception",    { fg = c.keyword })
  hi("String",       { fg = c.string })
  hi("Character",    { fg = c.string })
  hi("Identifier",   { fg = c.fg })
  hi("Function",     { fg = c.fg })
  hi("Type",         { fg = c.type })
  hi("StorageClass", { fg = c.type })
  hi("Structure",    { fg = c.type })
  hi("Typedef",      { fg = c.type })
  hi("Constant",     { fg = c.type })
  hi("Number",       { fg = c.type })
  hi("Boolean",      { fg = c.type })
  hi("Float",        { fg = c.type })
  hi("Operator",     { fg = c.punctuation })
  hi("Delimiter",    { fg = c.punctuation })
  hi("Special",      { fg = c.parameter })
  hi("PreProc",      { fg = c.parameter })
  hi("Include",      { fg = c.parameter })
  hi("Define",       { fg = c.parameter })
  hi("Macro",        { fg = c.parameter })

  -- ── Treesitter ─────────────────────────────────────────────────────────
  hi("@keyword",               { fg = c.keyword })
  hi("@keyword.function",      { fg = c.keyword })
  hi("@keyword.return",        { fg = c.keyword })
  hi("@keyword.operator",      { fg = c.punctuation })
  hi("@string",                { fg = c.string })
  hi("@string.escape",         { fg = c.warning })
  hi("@comment",               { fg = c.comment, italic = true })
  hi("@variable",              { fg = c.fg })
  hi("@variable.builtin",      { fg = c.type })
  hi("@function",              { fg = c.fg })
  hi("@function.call",         { fg = c.fg })
  hi("@function.builtin",      { fg = c.type })
  hi("@method",                { fg = c.fg })
  hi("@method.call",           { fg = c.fg })
  hi("@parameter",             { fg = c.parameter })
  hi("@type",                  { fg = c.type })
  hi("@type.builtin",          { fg = c.type })
  hi("@field",                 { fg = c.fg })
  hi("@property",              { fg = c.fg })
  hi("@number",                { fg = c.type })
  hi("@boolean",               { fg = c.type })
  hi("@float",                 { fg = c.type })
  hi("@constant",              { fg = c.type })
  hi("@constant.builtin",      { fg = c.type })
  hi("@operator",              { fg = c.punctuation })
  hi("@punctuation.bracket",   { fg = c.punctuation })
  hi("@punctuation.delimiter", { fg = c.punctuation })
  hi("@tag",                   { fg = c.keyword })
  hi("@tag.attribute",         { fg = c.parameter })
  hi("@tag.delimiter",         { fg = c.punctuation })
  hi("@namespace",             { fg = c.type })
  hi("@constructor",           { fg = c.type })
  hi("@include",               { fg = c.parameter })
end

return M
