local M = {}

local function hi(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

function M.load(c)
  -- ── Base UI ────────────────────────────────────────────────────────
  hi("Normal",        { fg = c.fg,      bg = c.bg })
  hi("NormalFloat",   { fg = c.fg,      bg = c.bg })
  hi("FloatBorder",   { fg = c.ui_mid })
  hi("FloatTitle",    { fg = c.keyword })
  hi("NormalNC",      { fg = c.fg,      bg = c.bg })
  hi("CursorLine",    { bg = c.cursorline })
  hi("CursorLineNr",  { fg = c.keyword, bg = c.cursorline })
  hi("Visual",        { bg = c.visual })
  hi("Search",        { fg = c.bg,      bg = c.warning })
  hi("IncSearch",     { fg = c.bg,      bg = c.keyword })
  hi("StatusLine",    { fg = c.fg,      bg = c.ui_dark })
  hi("StatusLineNC",  { fg = c.comment, bg = c.ui_dark })
  hi("WinSeparator",  { fg = c.ui_mid })
  hi("VertSplit",     { fg = c.ui_mid })  -- deprecated alias for WinSeparator, kept for compat
  hi("LineNr",        { fg = c.comment })
  hi("SignColumn",    { bg = c.bg })
  hi("Pmenu",         { fg = c.fg,      bg = c.ui_dark })
  hi("PmenuSel",      { fg = c.bg,      bg = c.keyword })
  hi("PmenuSbar",     { bg = c.ui_mid })
  hi("PmenuThumb",    { bg = c.fg })
  hi("ColorColumn",   { bg = c.cursorline })
  hi("Folded",        { fg = c.comment, bg = c.cursorline })
  hi("TabLine",       { fg = c.comment, bg = c.ui_dark })
  hi("TabLineSel",    { fg = c.fg,      bg = c.bg })
  hi("TabLineFill",   { bg = c.bg })
  hi("Title",         { fg = c.keyword, bold = true })

  -- ── Legacy syntax ──────────────────────────────────────────────────────
  hi("Comment",      { fg = c.comment,     italic = true })
  hi("Keyword",      { fg = c.keyword })
  hi("Statement",    { fg = c.keyword })
  hi("Conditional",  { fg = c.keyword })
  hi("Repeat",       { fg = c.keyword })
  hi("Label",        { fg = c.keyword })
  hi("Exception",    { fg = c.keyword })
  hi("String",       { fg = c.string })
  hi("Character",    { fg = c.string })
  hi("Identifier",   { fg = c.fg })
  hi("Function",     { fg = c.fg })
  hi("Type",         { fg = c.type })
  hi("StorageClass", { fg = c.type })
  hi("Structure",    { fg = c.type })
  hi("Typedef",      { fg = c.type })
  hi("Constant",     { fg = c.type })
  hi("Number",       { fg = c.type })
  hi("Boolean",      { fg = c.type })
  hi("Float",        { fg = c.type })
  hi("Operator",     { fg = c.punctuation })
  hi("Delimiter",    { fg = c.punctuation })
  hi("Special",      { fg = c.parameter })
  hi("PreProc",      { fg = c.parameter })
  hi("Include",      { fg = c.parameter })
  hi("Define",       { fg = c.parameter })
  hi("Macro",        { fg = c.parameter })

  -- ── Treesitter ─────────────────────────────────────────────────────────
  hi("@keyword",               { fg = c.keyword })
  hi("@keyword.function",      { fg = c.keyword })
  hi("@keyword.return",        { fg = c.keyword })
  hi("@keyword.operator",      { fg = c.punctuation })
  hi("@string",                { fg = c.string })
  hi("@string.escape",         { fg = c.warning })
  hi("@comment",               { fg = c.comment, italic = true })
  hi("@variable",              { fg = c.fg })
  hi("@variable.builtin",      { fg = c.type })
  hi("@function",              { fg = c.fg })
  hi("@function.call",         { fg = c.fg })
  hi("@function.builtin",      { fg = c.type })
  hi("@method",                { fg = c.fg })
  hi("@method.call",           { fg = c.fg })
  hi("@parameter",             { fg = c.parameter })
  hi("@type",                  { fg = c.type })
  hi("@type.builtin",          { fg = c.type })
  hi("@field",                 { fg = c.fg })
  hi("@property",              { fg = c.fg })
  hi("@number",                { fg = c.type })
  hi("@boolean",               { fg = c.type })
  hi("@float",                 { fg = c.type })
  hi("@constant",              { fg = c.type })
  hi("@constant.builtin",      { fg = c.type })
  hi("@operator",              { fg = c.punctuation })
  hi("@punctuation.bracket",   { fg = c.punctuation })
  hi("@punctuation.delimiter", { fg = c.punctuation })
  hi("@tag",                   { fg = c.keyword })
  hi("@tag.attribute",         { fg = c.parameter })
  hi("@tag.delimiter",         { fg = c.punctuation })
  hi("@namespace",             { fg = c.type })
  hi("@constructor",           { fg = c.type })
  hi("@include",               { fg = c.parameter })

  -- ── Markdown / markup (treesitter @markup.*) ───────────────────────────────
  hi("@markup.heading.1",         { fg = c.keyword,   bold = true })
  hi("@markup.heading.2",         { fg = c.keyword,   bold = true })
  hi("@markup.heading.3",         { fg = c.keyword,   bold = true })
  hi("@markup.heading.4",         { fg = c.keyword,   bold = true })
  hi("@markup.heading.5",         { fg = c.keyword,   bold = true })
  hi("@markup.heading.6",         { fg = c.keyword,   bold = true })
  hi("@markup.heading.1.marker",  { fg = c.punctuation })
  hi("@markup.heading.2.marker",  { fg = c.punctuation })
  hi("@markup.heading.3.marker",  { fg = c.punctuation })
  hi("@markup.heading.4.marker",  { fg = c.punctuation })
  hi("@markup.heading.5.marker",  { fg = c.punctuation })
  hi("@markup.heading.6.marker",  { fg = c.punctuation })
  hi("@markup.raw.inline",        { fg = c.fg, bg = c.ui_dark })
  hi("@markup.raw.block",         { fg = c.fg })
  hi("@markup.raw.delimiter",     { fg = c.punctuation })
  hi("@markup.link",              { fg = c.parameter })
  hi("@markup.link.label",        { fg = c.parameter })
  hi("@markup.link.url",          { fg = c.hint,      underline = true })
  hi("@markup.italic",            { fg = c.fg,        italic = true })
  hi("@markup.strong",            { fg = c.fg,        bold = true })
  hi("@markup.strikethrough",     { fg = c.comment,   strikethrough = true })
  hi("@markup.list",              { fg = c.punctuation })
  hi("@markup.list.checked",      { fg = c.hint })
  hi("@markup.list.unchecked",    { fg = c.comment })
  hi("@markup.quote",             { fg = c.comment,   italic = true })

  -- ── LSP diagnostics ────────────────────────────────────────────────────
  hi("DiagnosticError",          { fg = c.error })
  hi("DiagnosticWarn",           { fg = c.warning })
  hi("DiagnosticInfo",           { fg = c.hint })  -- intentionally same as Hint; no distinct info color in palette
  hi("DiagnosticHint",           { fg = c.hint })
  hi("DiagnosticUnderlineError", { undercurl = true, sp = c.error })
  hi("DiagnosticUnderlineWarn",  { undercurl = true, sp = c.warning })
  hi("DiagnosticUnderlineInfo",  { undercurl = true, sp = c.hint })
  hi("DiagnosticUnderlineHint",  { undercurl = true, sp = c.hint })
  hi("LspReferenceText",         { bg = c.cursorline })
  hi("LspReferenceRead",         { bg = c.cursorline })
  hi("LspReferenceWrite",        { bg = c.cursorline })

  -- ── LSP semantic tokens ────────────────────────────────────────────
  hi("@lsp.type.keyword",    { link = "@keyword" })
  hi("@lsp.type.string",     { link = "@string" })
  hi("@lsp.type.comment",    { link = "@comment" })
  hi("@lsp.type.variable",   { link = "@variable" })
  hi("@lsp.type.function",   { link = "@function" })
  hi("@lsp.type.method",     { link = "@method" })
  hi("@lsp.type.parameter",  { link = "@parameter" })
  hi("@lsp.type.type",       { link = "@type" })
  hi("@lsp.type.class",      { link = "@type" })
  hi("@lsp.type.interface",  { link = "@type" })
  hi("@lsp.type.namespace",  { link = "@namespace" })
  hi("@lsp.type.property",   { link = "@property" })
  hi("@lsp.type.number",       { link = "@number" })
  hi("@lsp.type.operator",     { link = "@operator" })
  hi("@lsp.type.enum",         { link = "@type" })
  hi("@lsp.type.enumMember",   { link = "@variable" })
  hi("@lsp.type.decorator",    { link = "@parameter" })
  hi("@lsp.type.macro",        { link = "@keyword" })

  -- ── Noice ──────────────────────────────────────────────────────────
  hi("NoiceCmdlinePopup",              { fg = c.fg,      bg = c.bg })
  hi("NoiceCmdlinePopupBorder",        { fg = c.ui_mid })
  hi("NoiceCmdlinePopupBorderCmdline", { fg = c.ui_mid })
  hi("NoiceCmdlinePopupBorderSearch",  { fg = c.warning })
  hi("NoiceCmdlinePopupBorderFilter",  { fg = c.hint })
  hi("NoiceCmdlinePopupBorderHelp",    { fg = c.comment })
  hi("NoiceCmdlinePopupBorderLua",     { fg = c.keyword })
  hi("NoiceCmdlinePopupTitle",         { fg = c.keyword })
  hi("NoiceCmdlineIcon",               { fg = c.keyword })
  hi("NoiceCmdlineIconSearch",         { fg = c.warning })

  -- ── render-markdown.nvim ───────────────────────────────────────────
  hi("RenderMarkdownCode",        { bg = c.code_bg })
  hi("RenderMarkdownCodeInline",  { bg = c.code_bg })

  -- ── Snacks dashboard ───────────────────────────────────────────────
  hi("SnacksDashboardHeader",  { fg = c.keyword,    bold = true })
  hi("SnacksDashboardTitle",   { fg = c.keyword,    bold = true })
  hi("SnacksDashboardDesc",    { fg = c.parameter })
  hi("SnacksDashboardKey",     { fg = c.warning })
  hi("SnacksDashboardIcon",    { fg = c.hint })
  hi("SnacksDashboardFooter",  { fg = c.comment })
  hi("SnacksDashboardDir",     { fg = c.comment })
  hi("SnacksDashboardFile",    { fg = c.fg })
  hi("SnacksDashboardNormal",  { fg = c.fg,         bg = c.bg })
  hi("SnacksDashboardSpecial", { fg = c.parameter })

  -- ── Diff ───────────────────────────────────────────────────────────
  hi("DiffAdd",    { fg = c.hint,    bg = c.diff_add_bg })
  hi("DiffChange", { fg = c.warning, bg = c.diff_chg_bg })
  hi("DiffDelete", { fg = c.error,   bg = c.diff_del_bg })
  hi("DiffText",   { fg = c.fg,      bg = c.diff_chg_bg })
end

return M
